language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t patbak15/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true patbak15/react-test npm test

after_success:
  - docker build -t patbak15/multi-client ./client
  - docker build -t patbak15/multi-nginx ./nginx
  - docker build -t patbak15/multi-server ./server
  - docker build -t patbak15/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those imagesw and push them to docker hub
  - docker push patbak15/multi-client
  - docker push patbak15/multi-nginx
  - docker push patbak15/multi-server
  - docker push patbak15/multi-worker
